services:
  app:
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    environment:
      APP_ENV: "${APP_ENV:-development}"
    ports:
      - "${APP_PORT:-3000}:3000"
      - "${PROXY_PORT:-8080}:8080"
    volumes:
      - ./:/app
